spring:
  # 开启日志
  logging:
    level:
      org.springframework.web: DEBUG,CONSOLE
    config: classpath:logback.xml

  # 开启kafka集群
  kafka:
    #以逗号分隔的主机：端口对列表，用于建立与Kafka群集的初始连接
    bootstrap-servers: 192.168.0.9:9092,192.168.0.11:9092,192.168.0.12:9092
    consumer:
      #群组ID
      group-id: default_consumer_group
      #如果为true，则消费者的偏移量将在后台定期提交，默认值为true
      enable-auto-commit: true
      #如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
      auto-commit-interval: PT5S
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer